# Dockerfile
FROM python:3.9

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 5001

# Command to run on container start
CMD ["python", "tournement.py"]
